export const POSTS = 'POSTS';
export const REQUEST_TWEETS_FAILED = 'REQUEST_TWEETS_FAILED';
export const TERM = 'TERM';
export const DEBOUNCED_TERM = 'DEBOUNCED_TERM';
export const FILTERED_HASH_TAGS = 'FILTERED_HASH_TAGS';